@startuml

object "User entry point (Facade)" as facade {
    1. address create_erc721(name: String)
    2. address create_erc1155(name: String)
    3. address create_condensed(name: String)
    4. address create_erc20(name: String, symbol: String)
    5. address[] create_light_erc721(\n\t name: String, contracts: Int, tokens: Int)
}

object "Factory \n ERC-721" as factory721
object "Factory \n ERC-1155" as factory1155
object "Factory \n condensed NFT" as factory_condensed
object "Factory \n легковесных \n ERC-721" as factory_light_721
object "Factory \n ERC-20" as factory20

object "ERC-721 \n collection" as erc721
object "ERC-1155 \n collection" as erc1155
object "Condensed \n collection" as condensed
object "ERC-20 \n cuurency" as erc20
object "Light weighted \n ERC-721 \n collection" as light_erc721

object "«interface» \n Metadata repository" as repo_metadata {
    pair<address, uint256> get()
}
object "Good metadata \n repository" as grm

grm .l.|> repo_metadata

facade -d-> factory721
facade -d-> factory1155
facade -d-> factory_condensed
facade -d-> factory20
facade -d-> factory_light_721

factory721 -d-> erc721
factory1155 -d-> erc1155
factory_condensed -d-> condensed
factory20 -d-> erc20
factory_light_721 -d-> light_erc721

erc721 .d-> repo_metadata
erc1155 .d-> repo_metadata
condensed .d-> repo_metadata
light_erc721 .d-> repo_metadata

note right of grm: Used by all collection contracts

@enduml
