@startuml
left to right direction

object "ERC-20 \n контракт" as erc20_c
object "ERC-721 \n контракт" as erc721_c
object "ERC-1155 \n контракт" as erc1155_c

object "Уникальный \n ERC-20 токен" as token_20
object "Уникальный \n ERC-721 токен" as token_721
object "Уникальный \n ERC-1155 токен" as token_1155

package "Спецификации \n контрактов        " as erc #DDDDDD {
    object "«interface» \nERC-20" as erc20
    object "«interface» \nERC-721" as erc721
    object "«interface» \nERC-1155" as erc1155
    object "«interface» \nERC-173" as erc173
    erc173 .> erc721
    erc173 .> erc1155
}

package "Внешние \n аккаунты" as wallet #DDDDDD {
    object "Аккаунт \n владельца \n токена" as token_owner
    object "Аккаунт \n владельца \n контракта" as contract_owner
}

erc20 <|.. erc20_c
erc721 <|.. erc721_c
erc1155 <|.. erc1155_c

erc20_c "1" -- "1" token_20
erc721_c "1" o-- "1..*" token_721
erc1155_c "1" o-- "1..*" token_1155

token_20 "1" -- "1..*" token_owner
token_721 "1" --- "1    " token_owner
token_1155 "1" -- "\n    1..*" token_owner

token_20 -r[hidden]- token_721
token_721 -r[hidden]- token_1155
token_1155 -r[hidden]- token_20

contract_owner .> erc173

@enduml
