@startuml
left to right direction

object "ERC20 \n контракт" as erc20_c
object "ERC721 \n контракт" as erc721_c
object "ERC1155 \n контракт" as erc1155_c

object "Уникальный \n ERC20 токен" as token_20
object "Уникальный \n ERC721 токен" as token_721
object "Уникальный \n ERC1155 токен" as token_1155

object "Метаданные \n токена" as metadata

package "Спецификации \n контрактов" as erc #DDDDDD {
    interface "ERC20" as erc20
    interface "ERC721" as erc721
    interface "ERC1155" as erc1155
    interface "ERC173" as erc173
    erc173 .> erc721
    erc173 .> erc1155
}

package "Внешние \n аккаунты" as wallet #DDDDDD {
    object "Аккаунт \n владельца \n токена" as token_owner
    object "Аккаунт \n владельца \n контракта" as contract_owner
}

erc20 <|.. erc20_c
erc721 <|.. erc721_c
erc1155 <|.. erc1155_c

erc20_c ||--|| token_20
erc721_c ||--|{ token_721
erc1155_c ||--|{ token_1155

token_20 ||--|{ token_owner
token_721 ||--|| token_owner
token_1155 ||--|{ token_owner

token_1155 }|-r-|| metadata
token_721 }|-r-|| metadata

token_20 }|-r[hidden]-|| token_721
token_721 }|-r[hidden]-|| token_1155
token_1155 }|-r[hidden]-|| token_20

erc173 -> contract_owner

@enduml
