@startuml
left to right direction

user as "Пользователь"
user -- (Создать контракт-коллекцию)
(Создать контракт-коллекцию) <|-- (Создать ERC-721 контракт)
(Создать контракт-коллекцию) <|-- (Создать ERC-1155 контракт)
(Создать контракт-коллекцию) <|-- (Создать контракт с\nконденсированными токенами)
(Создать контракт-коллекцию) <.. (Стать владельцем коллекции)
user -- (Создать контракт-валюту)
user -- (Посмотреть список контрактов)
user -- (Создать токены в\nсозданных контрактах)
(Создать токены в\nсозданных контрактах) <.. (Использовать метаданные \nдругого токена)
(Создать токены в\nсозданных контрактах) <.. (Использовать метаданные \nслучайного токена)
(Создать токены в\nсозданных контрактах) <.. (Задать метаданные токена)
@enduml
