name: Check quality

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - master

jobs:
  base:
    name: 'Base preparation'
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm i

  test:
    name: 'Run tests'
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: base
    steps:
      - name: Download external libraries
        run: ./load-external.sh
      - name: Run tests
        run: npx hardhat test

  lint:
    name: 'Run linter'
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: base
    steps:
      - name: Run linter
        run: npm run lint
