name: Check quality

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - master

jobs:
  quality:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
        if: steps.restore-cache.outputs.cache-hit != 'true'
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Download external libraries
        run: ./load-external.sh
      - name: Run tests
        run: npx hardhat test
